export const yt = (n) => "https://www.youtube.com/results?search_query=" + encodeURIComponent(n + " proper form technique");
const L = (g, view, primary, secondary, target, desc, cues) => ({ g, view, primary, secondary, target, desc, cues });

// Respects user's excluded lifts: no deadlift, RDL, walking lunge, single-arm DB row.
export const LIB = {
  // ---- CHEST ----
  "Barbell Bench Press": L("Chest", "front", ["chest"], ["frontDelts"], "Chest, Front Delts, Triceps",
    "The main horizontal press and your key upper-body strength driver. Keep it heavy while cutting.",
    ["Retract and pin the shoulder blades", "Lower to mid-chest with a slight arch", "Drive up and slightly back over the shoulders"]),
  "Incline Barbell Press": L("Chest", "front", ["chest"], ["frontDelts"], "Upper Chest, Front Delts",
    "Barbell incline targets the upper chest with heavy loading.", ["30–45° bench angle", "Lower to the upper chest", "Keep blades retracted"]),
  "Incline Dumbbell Press": L("Chest", "front", ["chest"], ["frontDelts"], "Upper Chest, Front Delts",
    "Dumbbells give a deeper, joint-friendly stretch on the upper chest.", ["Bench at 30°", "Lower for an upper-chest stretch", "Press up and slightly together"]),
  "Flat Dumbbell Press": L("Chest", "front", ["chest"], ["frontDelts"], "Chest, Triceps",
    "Dumbbell version of the flat press for a bigger range of motion.", ["Control the descent", "Wrists stacked over elbows", "Press without clashing the bells"]),
  "Pec Deck Fly": L("Chest", "front", ["chest"], [], "Chest (isolation)",
    "Constant-tension chest isolation — great low-fatigue stimulus on a cut.", ["Soft bend in the elbows", "Squeeze pecs at the front", "Control the negative"]),
  "Cable Crossover": L("Chest", "front", ["chest"], ["frontDelts"], "Chest (isolation)",
    "Cables keep tension through the whole range for a strong contraction.", ["Slight forward lean", "Bring hands together and down", "Squeeze, then control back"]),
  "Push-Up": L("Chest", "front", ["chest"], ["frontDelts"], "Chest, Triceps, Core",
    "Bodyweight staple you can do anywhere — great finisher.", ["Body in a straight line", "Elbows ~45° from torso", "Full lockout at the top"]),
  "Machine Chest Press": L("Chest", "front", ["chest"], ["frontDelts"], "Chest, Triceps",
    "Fixed-path press — safe to push close to failure with no spotter.", ["Handles at mid-chest height", "Press without shrugging", "Control the return"]),
  "Smith Machine Bench Press": L("Chest", "front", ["chest"], ["frontDelts"], "Chest, Triceps",
    "Guided-bar bench press — same stimulus, easier to bail out of.", ["Bar path fixed, still tuck elbows", "Lower to mid-chest", "Drive up under control"]),
  "Incline Cable Fly": L("Chest", "front", ["chest"], ["frontDelts"], "Upper Chest (isolation)",
    "Low-to-high cable angle biases the upper chest under constant tension.", ["Set pulleys low", "Sweep hands up and in", "Squeeze at the top, don't shrug"]),
  "Decline Dumbbell Press": L("Chest", "front", ["chest"], ["frontDelts"], "Lower Chest, Triceps",
    "Decline angle shifts emphasis to the lower chest fibers.", ["Bench declined ~15–20°", "Lower under control", "Press up and slightly in"]),
  "Weighted Dips": L("Chest", "front", ["chest"], ["frontDelts"], "Lower Chest, Triceps",
    "Add load once bodyweight dips get easy — big lower-chest builder.", ["Lean forward for chest emphasis", "Lower to a deep stretch", "Press up without swinging"]),

  // ---- BACK ----
  "Wide Grip Lat Pulldown": L("Back", "back", ["lats"], ["upperBack", "rearDelts"], "Lats, Upper Back",
    "Builds lat width for the V-taper.", ["Pull elbows down and in", "Bar to the upper chest", "Control the stretch at the top"]),
  "Lat Pulldown": L("Back", "back", ["lats"], ["upperBack", "rearDelts"], "Lats",
    "Vertical pull; vary the grip from your wide-grip day.", ["Chest up, slight lean", "Pull to the collarbone", "Feel the lats, not the arms"]),
  "Chest Supported Row": L("Back", "back", ["upperBack", "lats"], ["rearDelts", "traps"], "Mid Back, Lats",
    "Strict back thickness with zero lower-back strain — ideal in a deficit.", ["Let the pad take your weight", "Row to the lower ribs", "Squeeze the blades"]),
  "Seated Cable Row": L("Back", "back", ["lats", "upperBack"], ["rearDelts"], "Mid Back, Lats",
    "Horizontal pull with constant tension.", ["Sit tall, small lean to stretch", "Drive elbows back", "No lower-back heaving"]),
  "Barbell Row": L("Back", "back", ["lats", "upperBack"], ["rearDelts", "traps"], "Back (compound)",
    "Heavy horizontal pull for overall back mass.", ["Hinge to ~45°, flat back", "Row to the lower chest/belly", "Control — no jerking"]),
  "T-Bar Row": L("Back", "back", ["upperBack", "lats"], ["traps", "rearDelts"], "Mid Back",
    "Supported-feel heavy row that hammers the mid-back.", ["Neutral grip, flat back", "Drive elbows back", "Squeeze at the top"]),
  "Straight Arm Pulldown": L("Back", "back", ["lats"], [], "Lats (isolation)",
    "Isolates the lats through shoulder extension.", ["Slight elbow bend, locked", "Pull the bar to the thighs", "Feel the lats stretch and contract"]),
  "Assisted Pull-Up": L("Back", "back", ["lats"], ["upperBack", "rearDelts"], "Lats, Upper Back",
    "Machine-assisted bodyweight pull — builds toward strict pull-ups.", ["Full stretch at the bottom", "Pull chest toward the bar", "Lower with control, no dropping"]),
  "Single Arm Lat Pulldown": L("Back", "back", ["lats"], ["upperBack"], "Lats (unilateral)",
    "Unilateral pulldown to even out left/right lat development.", ["Anchor the working side", "Pull elbow down and back", "Control the stretch each rep"]),
  "Machine High Row": L("Back", "back", ["upperBack", "lats"], ["rearDelts"], "Mid Back",
    "Chest-supported machine row — thickness without spinal load.", ["Chest against the pad", "Drive elbows back and up", "Squeeze the shoulder blades"]),
  "Reverse Grip Cable Row": L("Back", "back", ["lats", "upperBack"], ["biceps"], "Lats, Biceps",
    "Underhand grip shifts more work onto the lats and biceps.", ["Palms up on the handle", "Row to the lower ribs", "Elbows brush the sides"]),
  "Pull-Up": L("Back", "back", ["lats"], ["upperBack", "rearDelts"], "Lats, Upper Back",
    "The bodyweight benchmark pull once you're strong enough for full reps.", ["Dead hang start", "Pull chin over the bar", "Lower fully under control"]),

  // ---- SHOULDERS ----
  "Overhead Press": L("Shoulders", "front", ["frontDelts", "sideDelts"], ["traps"], "Shoulders (compound)",
    "The main vertical press for shoulder strength and size.", ["Brace the core, glutes tight", "Press in a straight line", "Bar over mid-foot at lockout"]),
  "Machine Shoulder Press": L("Shoulders", "front", ["frontDelts", "sideDelts"], [], "Shoulders",
    "Stable pressing — safe to push near failure when tired.", ["Handles at shoulder height", "Press without shrugging", "Don't lock out harshly"]),
  "Dumbbell Lateral Raise": L("Shoulders", "front", ["sideDelts"], ["traps"], "Side Delts",
    "The key to shoulder width. High reps, strict form.", ["Lead with the elbows", "Raise to shoulder height", "Slight pour-the-jug tilt"]),
  "Cable Lateral Raise": L("Shoulders", "front", ["sideDelts"], [], "Side Delts",
    "Constant cable tension on the side delts.", ["Cable behind the body", "Lead with the elbow", "Controlled down"]),
  "Face Pull": L("Shoulders", "back", ["rearDelts"], ["traps", "upperBack"], "Rear Delts, Upper Back",
    "Shoulder-health insurance for the rear delts and rotators.", ["Cable at face height", "Pull to the forehead", "Elbows high, rotate hands back"]),
  "Rear Delt Fly": L("Shoulders", "back", ["rearDelts"], ["upperBack"], "Rear Delts",
    "Direct rear-delt work for 3D shoulders.", ["Hinge forward slightly", "Lead with elbows, wide arc", "Pause at the top"]),
  "Front Raise": L("Shoulders", "front", ["frontDelts"], [], "Front Delts",
    "Targets the front delts (usually a bonus after pressing).", ["Raise to eye level", "No swinging", "Controlled lowering"]),
  "Dumbbell Shoulder Press": L("Shoulders", "front", ["frontDelts", "sideDelts"], ["triceps"], "Shoulders",
    "Free-weight press with a bigger stabilizer demand than machines.", ["Start at ear height", "Press up without arching hard", "Control the descent"]),
  "Arnold Press": L("Shoulders", "front", ["frontDelts", "sideDelts"], ["traps"], "All-round Shoulders",
    "Rotating press that hits front and side delts through the arc.", ["Start palms facing you", "Rotate out as you press", "Reverse the rotation lowering"]),
  "Machine Lateral Raise": L("Shoulders", "front", ["sideDelts"], [], "Side Delts",
    "Fixed path lets you push side-delt sets hard with strict form.", ["Pads on the outside of the upper arm", "Raise without shrugging", "Slow negative"]),
  "Upright Row": L("Shoulders", "front", ["sideDelts", "traps"], [], "Side Delts, Traps",
    "Vertical pull that adds width to the shoulders and traps.", ["Grip just outside the thighs", "Lead with the elbows, pull to chest height", "Don't pull above shoulder height"]),
  "Landmine Press": L("Shoulders", "front", ["frontDelts"], ["chest"], "Front Delts, Chest",
    "Shoulder-friendly angled press — easy on cranky joints.", ["Bar in the rack of the shoulder", "Press up and slightly forward", "Control it back down"]),

  // ---- ARMS ----
  "Barbell Curl": L("Arms", "front", ["biceps"], ["forearms"], "Biceps",
    "Classic biceps mass builder; strict reps retain muscle on a cut.", ["Elbows pinned to sides", "No swinging", "Control the lowering"]),
  "EZ Bar Curl": L("Arms", "front", ["biceps"], ["forearms"], "Biceps",
    "Wrist-friendly angled bar, still loads the biceps heavily.", ["Elbows at your sides", "Curl under control", "Full squeeze at the top"]),
  "Incline Dumbbell Curl": L("Arms", "front", ["biceps"], ["forearms"], "Biceps (long head)",
    "Incline stretches the long head for peak development.", ["Lie back on a 45–60° bench", "Let arms hang, then curl", "Slow eccentric"]),
  "Hammer Curl": L("Arms", "front", ["biceps", "forearms"], [], "Biceps (brachialis), Forearms",
    "Neutral grip adds arm thickness.", ["Palms face each other", "Wrists neutral and firm", "No body english"]),
  "Rope Tricep Pushdown": L("Arms", "back", ["triceps"], [], "Triceps",
    "Cable triceps staple; spread the rope at the bottom.", ["Pin elbows to sides", "Spread the rope at lockout", "Torso still"]),
  "Overhead Cable Tricep Extension": L("Arms", "back", ["triceps"], [], "Triceps (long head)",
    "Overhead puts the long head on stretch — best for size.", ["Upper arms beside the head", "Full stretch behind the head", "Extend without flaring"]),
  "Skull Crushers": L("Arms", "back", ["triceps"], [], "Triceps",
    "EZ-bar lying extension for heavy triceps loading.", ["Lower to the forehead/behind", "Elbows pointed up", "Extend without flaring"]),
  "Dips": L("Arms", "front", ["chest"], ["frontDelts"], "Triceps, Lower Chest",
    "Bodyweight compound for triceps and lower chest.", ["Upright = triceps, lean = chest", "Lower to ~90°", "Don't shrug at the top"]),
  "Cable Curl": L("Arms", "front", ["biceps"], ["forearms"], "Biceps",
    "Constant tension biceps work — no dead spot at the top or bottom.", ["Elbows fixed at your sides", "Curl through the full range", "Control the negative"]),
  "Preacher Curl": L("Arms", "front", ["biceps"], [], "Biceps (short head)",
    "Pad locks the upper arm so the biceps do all the work.", ["Upper arms flat on the pad", "Don't bounce out of the bottom", "Squeeze at the top"]),
  "Machine Tricep Extension": L("Arms", "back", ["triceps"], [], "Triceps",
    "Fixed-path triceps isolation, easy to load progressively.", ["Elbows pinned at the pivot", "Extend to full lockout", "Control back to the stretch"]),
  "Close Grip Bench Press": L("Arms", "front", ["triceps"], ["chest"], "Triceps, Chest",
    "Compound press that lets you overload the triceps heavily.", ["Hands just inside shoulder width", "Elbows track close to the body", "Press up without flaring"]),
  "Diamond Push-Up": L("Arms", "front", ["triceps"], ["chest"], "Triceps, Chest",
    "Bodyweight triceps finisher — no equipment needed.", ["Hands form a diamond under the chest", "Elbows stay close to the body", "Full lockout at the top"]),

  // ---- LEGS ----
  "Barbell Squat": L("Legs", "front", ["quads"], ["abs"], "Quads, Glutes, Core",
    "Main lower-body strength lift — heavy 6–8s protect leg muscle in a deficit.", ["Brace hard before descending", "Sit to depth between the hips", "Drive through mid-foot"]),
  "Hack Squat": L("Legs", "front", ["quads"], [], "Quads, Glutes",
    "Machine squat that hammers the quads on a fixed path.", ["Feet slightly low for quads", "Descend deep and controlled", "Drive through the whole foot"]),
  "Leg Press": L("Legs", "front", ["quads"], [], "Quads, Glutes",
    "Loadable quad work without spinal fatigue.", ["Feet shoulder-width", "Lower to ~90°", "Don't lock out hard"]),
  "Goblet Squat": L("Legs", "front", ["quads"], ["abs"], "Quads, Core",
    "Simple, joint-friendly squat with a dumbbell — great warm-up or main.", ["Hold the bell at the chest", "Elbows inside the knees at the bottom", "Chest tall"]),
  "Bulgarian Split Squat": L("Legs", "front", ["quads"], ["abs"], "Quads, Glutes",
    "Single-leg builder for balanced legs (not walking lunges).", ["Rear foot on a bench", "Drop straight down", "Drive through the front heel"]),
  "Leg Extension": L("Legs", "front", ["quads"], [], "Quads (isolation)",
    "Pure quad isolation and a strong finisher.", ["Pause and squeeze at the top", "Control the negative", "Point toes to bias the sweep"]),
  "Lying Leg Curl": L("Legs", "back", ["hamstrings"], ["calves"], "Hamstrings",
    "Direct hamstring flexion — essential since we skip deadlift variations.", ["Hips pressed into the pad", "Curl all the way up", "Slow eccentric"]),
  "Seated Leg Curl": L("Legs", "back", ["hamstrings"], ["calves"], "Hamstrings",
    "Seated version emphasises the hamstrings under stretch.", ["Thighs locked down", "Curl fully under", "Controlled release"]),
  "Hip Thrust": L("Legs", "back", ["glutes"], ["hamstrings"], "Glutes, Hamstrings",
    "The best direct glute builder — fills the gap left by skipping deadlifts.", ["Chin tucked, ribs down", "Drive hips to full lockout", "Squeeze hard at the top"]),
  "Standing Calf Raise": L("Legs", "back", ["calves"], [], "Calves (gastrocnemius)",
    "Straight-leg raise for the larger calf muscle.", ["Full stretch at the bottom", "Rise onto the big toe", "Pause at the top"]),
  "Seated Calf Raise": L("Legs", "back", ["calves"], [], "Calves (soleus)",
    "Bent knee targets the soleus.", ["Deep stretch each rep", "Slow tempo", "Squeeze at the top"]),
  "Front Squat": L("Legs", "front", ["quads"], ["abs"], "Quads, Core",
    "Front-loaded squat that's brutal on the quads and upright posture.", ["Bar rests on the front delts", "Elbows up, torso upright", "Sit straight down between the hips"]),
  "Smith Machine Squat": L("Legs", "front", ["quads"], ["abs"], "Quads, Glutes",
    "Guided-bar squat — lets you push hard without balance worries.", ["Feet slightly forward of the bar", "Descend under control", "Drive up through the whole foot"]),
  "Walking Step-Up": L("Legs", "front", ["quads"], ["glutes"], "Quads, Glutes",
    "Single-leg step pattern that builds balanced leg strength.", ["Step onto a knee-height box", "Drive through the front heel", "Stand tall at the top, don't push off the back foot"]),
  "Glute Bridge": L("Legs", "back", ["glutes"], ["hamstrings"], "Glutes",
    "Bodyweight/light-load glute builder, easy on the lower back.", ["Feet hip-width, knees bent", "Drive hips up, squeeze glutes", "Lower under control"]),
  "Machine Hip Abduction": L("Legs", "back", ["glutes"], [], "Glutes (medius)",
    "Isolates the outer glutes — good for hip stability and shape.", ["Sit tall, back against the pad", "Push knees outward against resistance", "Control the return"]),

  // ---- CORE ----
  "Hanging Leg Raise": L("Core", "front", ["abs"], [], "Lower Abs",
    "Hardcore lower-ab work off a bar.", ["No swinging", "Curl the pelvis up", "Lower under control"]),
  "Cable Crunch": L("Core", "front", ["abs"], [], "Abs",
    "Loadable ab flexion for progressive overload.", ["Hips fixed, hinge at the spine", "Crunch down with the abs", "Control back up"]),
  "Plank": L("Core", "front", ["abs"], [], "Core (isometric)",
    "Simple anti-extension core stability hold.", ["Straight line head-to-heels", "Brace and squeeze glutes", "Don't let the hips sag"]),
  "Machine Ab Crunch": L("Core", "front", ["abs"], [], "Abs",
    "Loadable, joint-friendly ab flexion — easy to progress weekly.", ["Hips fixed against the pad", "Crunch down through the ribs", "Control the return, don't bounce"]),
  "Cable Woodchop": L("Core", "front", ["abs"], [], "Obliques, Core",
    "Rotational core work that carries over to real-world twisting strength.", ["Pivot the back foot as you rotate", "Pull from high to low (or low to high)", "Control the return, don't yank"]),
  "Hollow Body Hold": L("Core", "front", ["abs"], [], "Core (isometric)",
    "Bodyweight anti-extension hold — no equipment needed.", ["Lower back pressed into the floor", "Arms and legs extended, held just off the ground", "Breathe steadily, don't let the back arch"]),
  "Ab Wheel Rollout": L("Core", "front", ["abs"], [], "Abs, Core",
    "Advanced anti-extension move — very effective once you're ready for it.", ["Start on your knees", "Roll out only as far as you can control", "Brace hard and pull back to start"]),
  "Russian Twist": L("Core", "front", ["abs"], [], "Obliques",
    "Simple rotational core finisher, weighted or bodyweight.", ["Lean back to ~45°, feet up or down", "Rotate the torso side to side", "Keep the movement controlled, not flung"]),
};

export const GROUPS = ["Chest", "Back", "Shoulders", "Legs", "Arms", "Core"];
